apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: registry.container-registry/blog
      context: ../jh7app
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
