apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-app
  namespace: app
  labels:
    team: app
spec:
  selector:
    matchLabels:
      app: blog
  endpoints:
    - port: web
      path: /prometheusMetrics
