apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: app
type: Opaque
data:
  secret: TldVMU1EVTROemN3TVRNd01ETTVZekZrTTJWaFlqWmlZelJtTjJJMk5XVTFZbUZqTkRKaU5qVm1ZalptTUdOaVpEWTJPR0UzWVRoall6ZGxZak5rTnpKa09ERmpNamt5TmpVMk1EYzFOamczT1dKak5qRmxOMkk0TmpBek56SmpOREUyT1RJMll6Tm1OakUzWVROaU5EazBZVEkxTUdGa016ZGxaV015TUdJPQ==
